## 1. Split this string

In [68]:
s = "Hi there Sam!"

# Basic Python

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [2]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


In [ ]:
planet = "Earth"
diameter = 12742

## 3. In this nest dictionary grab the word "hello"

In [3]:
planet = "Earth"
diameter = 12742
print ('The diameter of{} is {} kilometers.' . format(planet,diameter));

The diameter ofEarth is 12742 kilometers.


In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'] [3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print (array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [51]:
import numpy as np
array=np.arange(20,36)
print("Array of all the even integer from 20 to 35")
print(array)

Array of all the even integer from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [24]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b.T),axis=1)
np.concatenate((a,b),axis=None)



array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [59]:
import pandas as pd
# initalize data of lists.
data={'Name': ['Tom', 'nick','krish'], 
      'Age':[20,21,32]}
# create DataFrame
df=pd.DataFrame(data)
#print the output.
df



Name  Age
0    Tom   20
1   nick   21
2  krish   32

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [65]:
#importing pandas as pd
import pandas as pd
per1=pd.date_range(start ='1-01-2023',end='1-02-2023')
for val in per1:
  print(val)  
  


2023-01-01 00:00:00
2023-01-02 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [66]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [67]:
import pandas as pd
a=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
print(type(a))
for b in a:
  for j in b:
    print(j)
dt=zip(a)
df=pd.DataFrame(dt,columns=["d"])
print(type(df))
print(df)


<class 'list'>
1
aaa
22
2
bbb
25
3
ccc
24
<class 'pandas.core.frame.DataFrame'>
              d
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
